# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       # Remove local postgres connection variables
#       SUPABASE_DB_URL: postgresql://postgres:murirop@db.olzewzhpjspzcllhrqyk.supabase.co:5432/postgres
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#     dns:
#       - 8.8.8.8  # Google's DNS
#       - 1.1.1.1  # Cloudflare's DNS
#     volumes:
#       - ./backend:/app

# # Remove postgres service and volumes since we're using Supabase
# # volumes:
# #   postgres_data:

services:
  backend:
    build: ./backend
    # Option 1: Use host networking (Linux only, but works best)
    # network_mode: "host"
    
    # Option 2: Use port mapping with extra_hosts (works on all platforms)
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This helps on Linux
    
    environment:
      SUPABASE_DB_URL: postgresql://postgres:murirop@db.olzewzhpjspzcllhrqyk.supabase.co:5432/postgres
      # Option 3: Set a specific Ollama host
      # DATABASE_URL=postgresql://postgres:[YOUR-PASSWORD]@db.olzewzhpjspzcllhrqyk.supabase.co:5432/postgres
      # OLLAMA_HOST: "172.17.0.1:11434"  # Uncomment if using Linux
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    dns:
      - 8.8.8.8  # Google's DNS
      - 1.1.1.1  # Cloudflare's DNS
    volumes:
      - ./backend:/app