services:
  postgres:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: matcher
      POSTGRES_PASSWORD: matcherpass
      POSTGRES_DB: matcherdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: matcherdb
      DB_USER: matcher
      DB_PASSWORD: matcherpass
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
